-- MySQL Script generated by MySQL Workbench
-- Tue Nov 15 15:54:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u413142534_project8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u413142534_project8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u413142534_project8` DEFAULT CHARACTER SET utf8 ;
USE `u413142534_project8` ;

-- -----------------------------------------------------
-- Table `u413142534_project8`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`user` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`user` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `passwordHash` CHAR(60) NOT NULL,
  `name_first` VARCHAR(45) NOT NULL,
  `name_last` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `isAdmin` TINYINT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `u413142534_project8`.`roomGroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`roomGroup` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`roomGroup` (
  `roomGroupID` INT NOT NULL,
  PRIMARY KEY (`roomGroupID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u413142534_project8`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`room` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`room` (
  `roomID` VARCHAR(16) NOT NULL,
  `roomGroup_roomGroupID` INT NOT NULL,
  `roomName` VARCHAR(45) NULL,
  PRIMARY KEY (`roomID`, `roomGroup_roomGroupID`),
  UNIQUE INDEX `roomID_UNIQUE` (`roomID` ASC) VISIBLE,
  INDEX `fk_room_roomGroup1_idx` (`roomGroup_roomGroupID` ASC) VISIBLE,
  CONSTRAINT `fk_room_roomGroup1`
    FOREIGN KEY (`roomGroup_roomGroupID`)
    REFERENCES `u413142534_project8`.`roomGroup` (`roomGroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u413142534_project8`.`assignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`assignment` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`assignment` (
  `assignmentDate` DATE NOT NULL,
  `user_userID` INT NOT NULL,
  `roomGroup_roomGroupID` INT NOT NULL,
  PRIMARY KEY (`assignmentDate`, `user_userID`, `roomGroup_roomGroupID`),
  INDEX `fk_assignment_user1_idx` (`user_userID` ASC) VISIBLE,
  INDEX `fk_assignment_roomGroup1_idx` (`roomGroup_roomGroupID` ASC) VISIBLE,
  CONSTRAINT `fk_assignment_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `u413142534_project8`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assignment_roomGroup1`
    FOREIGN KEY (`roomGroup_roomGroupID`)
    REFERENCES `u413142534_project8`.`roomGroup` (`roomGroupID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u413142534_project8`.`formEntry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`formEntry` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`formEntry` (
  `room_roomID` VARCHAR(16) NOT NULL,
  `assignment_assignmentDate` DATE NOT NULL,
  `assignment_user_userID` INT NOT NULL,
  `completeTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_formEntry_room1_idx` (`room_roomID` ASC) VISIBLE,
  PRIMARY KEY (`room_roomID`, `assignment_assignmentDate`, `assignment_user_userID`),
  INDEX `fk_formEntry_assignment1_idx` (`assignment_assignmentDate` ASC, `assignment_user_userID` ASC) VISIBLE,
  CONSTRAINT `fk_formEntry_room1`
    FOREIGN KEY (`room_roomID`)
    REFERENCES `u413142534_project8`.`room` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formEntry_assignment1`
    FOREIGN KEY (`assignment_assignmentDate` , `assignment_user_userID`)
    REFERENCES `u413142534_project8`.`assignment` (`assignmentDate` , `user_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u413142534_project8`.`projector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`projector` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`projector` (
  `projectorID` INT NOT NULL AUTO_INCREMENT,
  `room_roomID` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`projectorID`, `room_roomID`),
  INDEX `fk_projector_room1_idx` (`room_roomID` ASC) VISIBLE,
  CONSTRAINT `fk_projector_room1`
    FOREIGN KEY (`room_roomID`)
    REFERENCES `u413142534_project8`.`room` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u413142534_project8`.`lampEntry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`lampEntry` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`lampEntry` (
  `projector_projectorID` INT NOT NULL,
  `formEntry_assignment_assignmentDate` DATE NOT NULL,
  `hours` INT NOT NULL,
  PRIMARY KEY (`projector_projectorID`, `formEntry_assignment_assignmentDate`),
  INDEX `fk_lampEntry_projector1_idx` (`projector_projectorID` ASC) VISIBLE,
  INDEX `fk_lampEntry_formEntry1_idx` (`formEntry_assignment_assignmentDate` ASC) VISIBLE,
  CONSTRAINT `fk_lampEntry_projector1`
    FOREIGN KEY (`projector_projectorID`)
    REFERENCES `u413142534_project8`.`projector` (`projectorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lampEntry_formEntry1`
    FOREIGN KEY (`formEntry_assignment_assignmentDate`)
    REFERENCES `u413142534_project8`.`formEntry` (`assignment_assignmentDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u413142534_project8`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`attribute` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`attribute` (
  `attributeName` VARCHAR(45) NOT NULL,
  `displayName` VARCHAR(45) NOT NULL,
  `categoryName` VARCHAR(45) NULL,
  PRIMARY KEY (`attributeName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u413142534_project8`.`roomAttribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `u413142534_project8`.`roomAttribute` ;

CREATE TABLE IF NOT EXISTS `u413142534_project8`.`roomAttribute` (
  `room_roomID` VARCHAR(16) NOT NULL,
  `attribute_attributeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`room_roomID`, `attribute_attributeName`),
  INDEX `fk_roomAttribute_attribute1_idx` (`attribute_attributeName` ASC) VISIBLE,
  CONSTRAINT `fk_roomAttribute_room1`
    FOREIGN KEY (`room_roomID`)
    REFERENCES `u413142534_project8`.`room` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roomAttribute_attribute1`
    FOREIGN KEY (`attribute_attributeName`)
    REFERENCES `u413142534_project8`.`attribute` (`attributeName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
