insert into roomAttribute ("N129","Lap3.5")
insert into roomAttribute ("N129","LapEthernet")
insert into roomAttribute ("N129","LapHDMI")
insert into roomAttribute ("N129","LapUSBC")
insert into roomAttribute ("N129","LapVGA")